name: Terraform and Ansible Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3


    - name: Configure AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV


    - name: Terraform Init
      run: terraform init
      working-directory: terraform


    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform


    - name: Get EC2 IP
      run: |
        echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
      working-directory: terraform


    - name: Wait for SSH
      run: sleep 60


    - name: Add EC2 to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts


    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/devops-key.pem
        chmod 600 ~/.ssh/devops-key.pem


    - name: Install Python 3.11 on EC2
      run: |
       ssh -i ~/.ssh/devops-key.pem ubuntu@$EC2_IP -o StrictHostKeyChecking=no << 'EOF'
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update
        sudo apt install -y python3.11 python3.11-venv python3.11-distutils
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
        python3 --version
       EOF

       
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

       
    - name: Create inventory
      run: |
        echo "[web]" > ansible/inventory
        echo "$EC2_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key.pem ansible_python_interpreter=/usr/bin/python3.11 ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ansible/inventory
    
    - name: Run Ansible playbook
      run: ansible-playbook -i inventory install_docker.yml
      working-directory: ansible
